### ISSUE TITLE
Unsupported major.minor version 51.0

### ISSUE THREAD

**Issue by rlzijdeman** [egonw/rrdf#37]
Hi,

I'm trying to run the examples from the sparql.remote help page, but in both cases I am treated to a warning and get no output:
"In .jcall("com/github/egonw/rrdf/RJenaHelper", "Lcom/github/egonw/rrdf/StringMatrix;",  :
  java.lang.UnsupportedClassVersionError: com/github/egonw/rrdf/RJenaHelper : Unsupported major.minor version 51.0"

I'm not sure what that means. Any ideas how I can resolve it?

Best,

Richard

**Comment by konradedgar** [comment]
I've experience the same problem when trying to execute `load.rdf` command.

**Comment by egonw** [comment]
It practically means that you're using Java6 or older. You need Java7 or better even Java8 (which is also just faster). More info about the major.minor versioning in Java can be found in [this StackOverflow post](http://stackoverflow.com/questions/10382929/how-to-fix-unsupported-major-minor-version-51-0-error).

**Comment by egonw** [comment]
I have added a note in the README.md to indicate the Java7 (or higher) requirement.
