### ISSUE TITLE
Typo in rrdf/R/add.data.triple.R - dataTyime should be dateTime

### ISSUE THREAD

**Issue by MarcJAndersen** [egonw/rrdf#39]
diff --git a/rrdf/R/add.data.triple.R b/rrdf/R/add.data.triple.R
    index 4138206..51ba8d1 100644
    --- a/rrdf/R/add.data.triple.R
    +++ b/rrdf/R/add.data.triple.R
    @@ -28,7 +28,7 @@ add.data.triple <- function(store,
                        "normalizedString", "string", "token", "byte", "decimal", "float",
                        "int", "integer", "long", "negativeInteger", "nonNegativeInteger",
                        "nonPositiveInteger", "positiveInteger", "short", "unsignedByte",
        -                       "unsignedInt", "unsignedLong", "unsignedShort", "date", "dataTyime",
        +                       "unsignedInt", "unsignedLong", "unsignedShort", "date", "dateTime",
                        "duration", "gDay", "gMonth", "gMonthDay", "gYear", "gYearMonth",
                        "time")
                if (!(type %in% types))

**Comment by MarcJAndersen** [comment]
Thanks for the quick response! RRDF is used in (https://github.com/MarcJAndersen/rrdfqbcrnd0) to develop "standard models and technical standards for the storage and usage of analysis results data and metadata to support clinical and non-clinical applications."

**Comment by egonw** [comment]
Cool!
