### ISSUE TITLE
In rrdf/R/add.data.triple.R - add double, and possibly also QName and NOTATION

### ISSUE THREAD

**Issue by MarcJAndersen** [egonw/rrdf#40]
In rrdf/R/add.data.triple.R - add double. Maybe also also QName and NOTATION to have all the primitive datatypes in XML Schema Part 2: Datatypes Second Edition, section 3.2 Primitive datatypes in (http://www.w3.org/TR/xmlschema-2/#built-in-primitive-datatypes). The following are not stated in the types list. 
- 3.2.5 double
- 3.2.18 QName
- 3.2.19 NOTATION

BTW: Thanks for the rrdf package!

**Comment by egonw** [comment]
Thanks for the ping!

One thing I may need to look at later is the datatype it links to the N3 output... xsd:double works find, but not sure yet if xsd:NOTATION is something that exists...
